#!/bin/bash

# ==============================================================================
# UNLINK-TH: Project Structure Reporter
# ==============================================================================
# Description: Generates a markdown report of project directory structure
#              Verifies core configuration and injects DNA context.
# Domain: www.unlink-th.com
# ==============================================================================

# CONFIGURATION
OUTPUT_FILE="unlink-th-structure.md"
PROJECT_DOMAIN="www.unlink-th.com"
PROJECT_URL="https://www.unlink-th.com"
AI_DNA_FILE="config/AI-CONTEXT.DNA.md"
COMM_DNA_FILE="config/COMMUNICATION-DNA.md"
TYPES_FILE="types/index.ts"

# Directories allowed for scanning
WHITELIST_DIRS=(
  "app"
  "demo"
  "actions"
  "components"
  "lib"
  "hooks"
  "types"
  "public"
  "data"
  "constants"
  "providers"
  "content"
  "styles"
  "services"
  "config"
  "viewport"
)

# Required root-level configuration files
ROOT_FILES=(
  "eslint.config.mjs"
  "mdx-components.tsx"
  "next.config.ts"
  "package.json"
  "components.json"
  "tsconfig.json"
  "postcss.config.mjs"
  "types/index.ts"
)

# Regex to ignore non-essential or sensitive files
IGNORE_PATTERN="node_modules|\.git|\.next|\.DS_Store|__pycache__|\.env"

# START EXECUTION
rm -f "$OUTPUT_FILE"

echo "Scanning $PROJECT_DOMAIN project architecture..."

{
  echo "# Project Structure Report"
  echo ""
  echo "---"
  echo "> Project: $PROJECT_DOMAIN  "
  echo "> URL: $PROJECT_URL  "
  echo "> Generated on: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "---"
  echo ""

  # --- BRAND DNA CONTEXT INJECTION ---
  echo "## Brand DNA Context"
  echo ""
  
  # AI Context DNA
  if [ -f "$AI_DNA_FILE" ]; then
    echo "### AI Context Configuration"
    echo "Source: $AI_DNA_FILE"
    echo ""
    echo "\`\`\`markdown"
    cat "$AI_DNA_FILE"
    echo "\`\`\`"
    echo ""
  fi

  # Communication DNA
  if [ -f "$COMM_DNA_FILE" ]; then
    echo "### Communication Strategy"
    echo "Source: $COMM_DNA_FILE"
    echo ""
    echo "\`\`\`markdown"
    cat "$COMM_DNA_FILE"
    echo "\`\`\`"
    echo ""
  fi

  # --- ROOT CONFIGURATION FILES ---
  echo "## Root Configuration Files"
  echo "Validation of essential configuration at the project root."
  echo ""

  for file in "${ROOT_FILES[@]}"; do
    if [ -f "$file" ]; then
      echo "- **$file** (Verified)"
    else
      echo "- $file (MISSING)"
    fi
  done
  echo ""

  # --- TYPES VALIDATION ---
  echo "## Core Types Definitions"
  if [ -f "$TYPES_FILE" ]; then
    echo "Location: $TYPES_FILE"
    echo ""
    echo "\`\`\`typescript"
    cat "$TYPES_FILE"
    echo "\`\`\`"
  else
    echo "Error: $TYPES_FILE not found."
  fi
  echo ""

  # --- ARCHITECTURAL OVERVIEW ---
  echo "## Directory Tree"
  echo "Core business logic and UI layers."
  echo ""

  for dir in "${WHITELIST_DIRS[@]}"; do
    if [ -d "$dir" ]; then
      echo "### $dir"

      find "$dir" -maxdepth 10 -not -path '*/.*' \
        | grep -vE "$IGNORE_PATTERN" \
        | while read -r path; do

          depth=$(temp="${path//[^\/]/}"; echo "${#temp}")
          indent=$(printf '%*s' $((depth * 2)) "")
          name=$(basename "$path")

          if [ -d "$path" ]; then
            [[ "$path" != "$dir" ]] && echo "${indent}**$name/**"
          else
            echo "${indent}$name"
          fi
        done
      echo ""
    fi
  done

  echo "---"
  echo "Report generated by $PROJECT_DOMAIN Internal Automation."

} > "$OUTPUT_FILE"

echo "Success: Report saved to -> $OUTPUT_FILE"
