#!/bin/bash

# ==============================================================================
# 🛠️ www.unlink-th.com: Project Structure & Health Reporter
# ==============================================================================
# Description: Generates a comprehensive markdown report of the project structure.
# Features: Recursive directory mapping, dependency analysis, and pre-deploy sync.
# Domain: https://www.unlink-th.com
# ==============================================================================

# ⚙️ CONFIGURATION
OUTPUT_FILE="project-structure.md"
PRE_DEPLOY_REPORT="pre-deploy-report.md"
PROJECT_DOMAIN="www.unlink-th.com"
PROJECT_URL="https://www.unlink-th.com"

# Directories allowed for scanning (Strictly aligned with Next.js 15 App Router)
WHITELIST_DIRS=(
  "app"
  "actions"
  "components"
  "lib"
  "hooks"
  "types"
  "scripts"
  "public"
  "data"
  "constants"
  "providers"
  "content"
  "styles"
  "services"
  "config"
)

# Regex to ignore non-essential or sensitive files
IGNORE_PATTERN="node_modules|\.git|\.next|\.DS_Store|__pycache__|\.env"

# 🚀 START EXECUTION
rm -f "$OUTPUT_FILE"

echo "🔍 Scanning $PROJECT_DOMAIN project architecture..."

{
  echo "# 📁 Project Structure Report: $PROJECT_DOMAIN"
  echo ""
  echo "<!--"
  echo "  Domain: $PROJECT_DOMAIN"
  echo "  Canonical: $PROJECT_URL"
  echo "  Generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "  Type: Architecture / Health Report"
  echo "-->"
  echo ""
  echo "> **Project:** $PROJECT_DOMAIN"
  echo "> **URL:** $PROJECT_URL"
  echo "> **Generated on:** $(date '+%Y-%m-%d %H:%M:%S')"
  echo ""

  # --- 1. ARCHITECTURAL OVERVIEW ---
  echo "## 🌳 Directory Tree"
  echo "The following structure represents the core business logic and UI layers."
  echo ""

  for dir in "${WHITELIST_DIRS[@]}"; do
    if [ -d "$dir" ]; then
      echo "### 📂 $dir"

      find "$dir" -maxdepth 10 -not -path '*/.*' \
        | grep -vE "$IGNORE_PATTERN" \
        | while read -r path; do

          depth=$(temp="${path//[^\/]/}"; echo "${#temp}")
          indent=$(printf '%*s' $((depth * 2)) "")
          name=$(basename "$path")

          if [ -d "$path" ]; then
            [[ "$path" != "$dir" ]] && echo "${indent}📂 **$name/**"
          else
            echo "${indent}📄 $name"
          fi
        done

      echo ""
    fi
  done

  # --- 2. DEPENDENCY ANALYSIS ---
  echo "## 📦 Project Dependencies"
  if [ -f "package.json" ]; then
    echo "Current configuration in \`package.json\`:"
    echo '```json'
    if command -v jq >/dev/null 2>&1; then
      jq '{name, version, scripts, dependencies, devDependencies}' package.json
    else
      cat package.json
    fi
    echo '```'
  else
    echo "> ❌ Error: \`package.json\` not found in root directory."
  fi
  echo ""

  # --- 3. PRE-DEPLOYMENT HEALTH CHECK ---
  echo "## 📝 Deployment Status & Issues"
  echo "---"

  if [ -f "$PRE_DEPLOY_REPORT" ]; then
    if grep -qi "READY FOR DEPLOY" "$PRE_DEPLOY_REPORT"; then
      echo "### ✅ Final Status: **READY FOR DEPLOY**"
    else
      echo "### ❌ Final Status: **FIX REQUIRED**"
    fi
    echo ""

    if grep -q "### 📊 Route Statistics" "$PRE_DEPLOY_REPORT"; then
      echo "#### 📍 Production Route Map"
      echo "\`\`\`text"
      sed -n '/### 📊 Route Statistics/,/---/p' "$PRE_DEPLOY_REPORT" | \
        grep -vE "###|---" | sed '/^$/d'
      echo "\`\`\`"
    fi

    echo "#### ⚠️ Critical Issues Highlight"
    ERRORS=$(grep -E "❌|⚠️|[Ee]rror|[Ww]arning" "$PRE_DEPLOY_REPORT" | grep -v "###")
    if [ -z "$ERRORS" ]; then
      echo "Everything looks clean. No significant issues found in the latest report."
    else
      echo "$ERRORS"
    fi
  else
    echo "> ℹ️ Pre-deploy report (\`$PRE_DEPLOY_REPORT\`) is missing. Please run \`npm run check\` first."
  fi

  echo ""
  echo "---"
  echo "_Report generated by $PROJECT_DOMAIN Internal Automation._"

} > "$OUTPUT_FILE"

echo "✅ Success: Report saved to → $OUTPUT_FILE"